export const PERMISSION_CODES = {
  COMPANY_VIEW: "company.view",
  COMPANY_UPDATE: "company.update",
  COMPANY_SETTINGS_VIEW: "company.settings.view",
  COMPANY_SETTINGS_UPDATE: "company.settings.update",
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DEACTIVATE: "users.deactivate",
  TEAMS_VIEW: "teams.view",
  TEAMS_CREATE: "teams.create",
  TEAMS_UPDATE: "teams.update",
  TEAMS_DELETE: "teams.delete",
  TEAM_MEMBERS_VIEW: "team.members.view",
  TEAM_MEMBERS_ADD: "team.members.add",
  TEAM_MEMBERS_REMOVE: "team.members.remove",
  TEAM_MEMBERS_ROLE_UPDATE: "team.members.role.update",
  PROJECTS_VIEW: "projects.view",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_UPDATE: "projects.update",
  PROJECTS_ARCHIVE: "projects.archive",
  PROJECTS_DELETE: "projects.delete",
  PROJECT_MEMBERS_VIEW: "project.members.view",
  PROJECT_MEMBERS_ADD: "project.members.add",
  PROJECT_MEMBERS_REMOVE: "project.members.remove",
  PROJECT_MEMBERS_ROLE_UPDATE: "project.members.role.update",
  ROLES_VIEW: "roles.view",
  ROLES_ASSIGN: "roles.assign",
  PERMISSIONS_VIEW: "permissions.view",
  ISSUES_VIEW: "issues.view",
  ISSUES_CREATE: "issues.create",
  ISSUES_UPDATE: "issues.update",
  ISSUES_ASSIGN: "issues.assign",
  ISSUES_TRANSITION: "issues.transition",
  ISSUES_COMMENT_VIEW: "issues.comment.view",
  ISSUES_COMMENT_CREATE: "issues.comment.create",
  ISSUES_COMMENT_UPDATE: "issues.comment.update",
  ISSUES_COMMENT_DELETE: "issues.comment.delete",
  ISSUES_ATTACHMENT_UPLOAD: "issues.attachment.upload",
  ISSUES_ATTACHMENT_DELETE: "issues.attachment.delete",
  MESSAGES_READ: "messages.read",
  MESSAGES_SEND: "messages.send",
  MESSAGES_THREAD_CREATE: "messages.thread.create",
  SCRUM_SPRINT_VIEW: "scrum.sprint.view",
  SCRUM_SPRINT_CREATE: "scrum.sprint.create",
  SCRUM_SPRINT_UPDATE: "scrum.sprint.update",
  SCRUM_SPRINT_COMPLETE: "scrum.sprint.complete",
  SCRUM_BACKLOG_VIEW: "scrum.backlog.view",
  SCRUM_BACKLOG_UPDATE: "scrum.backlog.update",
  KANBAN_BOARD_VIEW: "kanban.board.view",
  KANBAN_ISSUE_MOVE: "kanban.issue.move",
  OKR_OBJECTIVE_VIEW: "okr.objective.view",
  OKR_OBJECTIVE_CREATE: "okr.objective.create",
  OKR_OBJECTIVE_UPDATE: "okr.objective.update",
  OKR_OBJECTIVE_CLOSE: "okr.objective.close",
  OKR_KEY_RESULT_MANAGE: "okr.key_result.manage",
  GANTT_VIEW: "gantt.view",
  GANTT_UPDATE: "gantt.update",
  ANALYTICS_VIEW: "analytics.view",
} as const;

export type PermissionCode = typeof PERMISSION_CODES[keyof typeof PERMISSION_CODES];

export type UiAction =
  | "company.view"
  | "company.settings.view"
  | "users.view"
  | "users.create"
  | "users.update"
  | "users.deactivate"
  | "teams.view"
  | "teams.create"
  | "teams.update"
  | "teams.delete"
  | "team.members.view"
  | "team.members.add"
  | "team.members.remove"
  | "team.members.role.update"
  | "projects.view"
  | "projects.create"
  | "projects.update"
  | "projects.archive"
  | "projects.delete"
  | "project.members.view"
  | "project.members.add"
  | "project.members.remove"
  | "project.members.role.update"
  | "issues.view"
  | "issues.create"
  | "issues.update"
  | "issues.assign"
  | "issues.transition"
  | "issues.comment.create"
  | "issues.comment.update"
  | "issues.comment.delete"
  | "issues.attachment.upload"
  | "issues.attachment.delete"
  | "messages.read"
  | "messages.send"
  | "messages.thread.create"
  | "scrum.sprint.view"
  | "scrum.sprint.create"
  | "scrum.sprint.update"
  | "scrum.sprint.complete"
  | "scrum.backlog.view"
  | "scrum.backlog.update"
  | "kanban.board.view"
  | "kanban.issue.move"
  | "okr.objective.view"
  | "okr.objective.create"
  | "okr.objective.update"
  | "okr.objective.close"
  | "okr.key_result.manage"
  | "gantt.view"
  | "gantt.update"
  | "analytics.view"
  | "platform.roles.view"
  | "platform.roles.assign"
  | "platform.permissions.view";

export const UI_ACTION_MATRIX: Record<UiAction, PermissionCode[]> = {
  "company.view": [PERMISSION_CODES.COMPANY_VIEW],
  "company.settings.view": [PERMISSION_CODES.COMPANY_SETTINGS_VIEW],
  "users.view": [PERMISSION_CODES.USERS_VIEW],
  "users.create": [PERMISSION_CODES.USERS_CREATE],
  "users.update": [PERMISSION_CODES.USERS_UPDATE],
  "users.deactivate": [PERMISSION_CODES.USERS_DEACTIVATE],
  "teams.view": [PERMISSION_CODES.TEAMS_VIEW],
  "teams.create": [PERMISSION_CODES.TEAMS_CREATE],
  "teams.update": [PERMISSION_CODES.TEAMS_UPDATE],
  "teams.delete": [PERMISSION_CODES.TEAMS_DELETE],
  "team.members.view": [PERMISSION_CODES.TEAM_MEMBERS_VIEW],
  "team.members.add": [PERMISSION_CODES.TEAM_MEMBERS_ADD],
  "team.members.remove": [PERMISSION_CODES.TEAM_MEMBERS_REMOVE],
  "team.members.role.update": [PERMISSION_CODES.TEAM_MEMBERS_ROLE_UPDATE],
  "projects.view": [PERMISSION_CODES.PROJECTS_VIEW],
  "projects.create": [PERMISSION_CODES.PROJECTS_CREATE],
  "projects.update": [PERMISSION_CODES.PROJECTS_UPDATE],
  "projects.archive": [PERMISSION_CODES.PROJECTS_ARCHIVE],
  "projects.delete": [PERMISSION_CODES.PROJECTS_DELETE],
  "project.members.view": [PERMISSION_CODES.PROJECT_MEMBERS_VIEW],
  "project.members.add": [PERMISSION_CODES.PROJECT_MEMBERS_ADD],
  "project.members.remove": [PERMISSION_CODES.PROJECT_MEMBERS_REMOVE],
  "project.members.role.update": [PERMISSION_CODES.PROJECT_MEMBERS_ROLE_UPDATE],
  "issues.view": [PERMISSION_CODES.ISSUES_VIEW],
  "issues.create": [PERMISSION_CODES.ISSUES_CREATE],
  "issues.update": [PERMISSION_CODES.ISSUES_UPDATE],
  "issues.assign": [PERMISSION_CODES.ISSUES_ASSIGN],
  "issues.transition": [PERMISSION_CODES.ISSUES_TRANSITION],
  "issues.comment.create": [PERMISSION_CODES.ISSUES_COMMENT_CREATE],
  "issues.comment.update": [PERMISSION_CODES.ISSUES_COMMENT_UPDATE],
  "issues.comment.delete": [PERMISSION_CODES.ISSUES_COMMENT_DELETE],
  "issues.attachment.upload": [PERMISSION_CODES.ISSUES_ATTACHMENT_UPLOAD],
  "issues.attachment.delete": [PERMISSION_CODES.ISSUES_ATTACHMENT_DELETE],
  "messages.read": [PERMISSION_CODES.MESSAGES_READ],
  "messages.send": [PERMISSION_CODES.MESSAGES_SEND],
  "messages.thread.create": [PERMISSION_CODES.MESSAGES_THREAD_CREATE],
  "scrum.sprint.view": [PERMISSION_CODES.SCRUM_SPRINT_VIEW],
  "scrum.sprint.create": [PERMISSION_CODES.SCRUM_SPRINT_CREATE],
  "scrum.sprint.update": [PERMISSION_CODES.SCRUM_SPRINT_UPDATE],
  "scrum.sprint.complete": [PERMISSION_CODES.SCRUM_SPRINT_COMPLETE],
  "scrum.backlog.view": [PERMISSION_CODES.SCRUM_BACKLOG_VIEW],
  "scrum.backlog.update": [PERMISSION_CODES.SCRUM_BACKLOG_UPDATE],
  "kanban.board.view": [PERMISSION_CODES.KANBAN_BOARD_VIEW],
  "kanban.issue.move": [PERMISSION_CODES.KANBAN_ISSUE_MOVE],
  "okr.objective.view": [PERMISSION_CODES.OKR_OBJECTIVE_VIEW],
  "okr.objective.create": [PERMISSION_CODES.OKR_OBJECTIVE_CREATE],
  "okr.objective.update": [PERMISSION_CODES.OKR_OBJECTIVE_UPDATE],
  "okr.objective.close": [PERMISSION_CODES.OKR_OBJECTIVE_CLOSE],
  "okr.key_result.manage": [PERMISSION_CODES.OKR_KEY_RESULT_MANAGE],
  "gantt.view": [PERMISSION_CODES.GANTT_VIEW],
  "gantt.update": [PERMISSION_CODES.GANTT_UPDATE],
  "analytics.view": [PERMISSION_CODES.ANALYTICS_VIEW],
  "platform.roles.view": [PERMISSION_CODES.ROLES_VIEW],
  "platform.roles.assign": [PERMISSION_CODES.ROLES_ASSIGN],
  "platform.permissions.view": [PERMISSION_CODES.PERMISSIONS_VIEW],
};
