CREATE TABLE tenant_registry (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  db_host VARCHAR(255) NOT NULL,
  db_port INTEGER NOT NULL,
  db_name VARCHAR(128) NOT NULL,
  db_schema VARCHAR(128),
  db_username VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  status VARCHAR(32) NOT NULL
);
