#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ENV_FILE="${ROOT_DIR}/.env"
if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "${ENV_FILE}"
  set +a
fi

: "${POSTGRES_USER:=phoenixtask}"
: "${POSTGRES_PASSWORD:=phoenixtask_local}"
: "${POSTGRES_DB:=postgres}"
: "${PHOENIXTASK_PG_PORT:=5433}"

: "${PHOENIXTASK_DB_HOST:=localhost}"
: "${PHOENIXTASK_DB_PORT:=${PHOENIXTASK_PG_PORT}}"
: "${PHOENIXTASK_CONTROL_DB:=phoenixtask_local}"
: "${PHOENIXTASK_DB_USER:=${POSTGRES_USER}}"
: "${PHOENIXTASK_DB_PASSWORD:=${POSTGRES_PASSWORD}}"

: "${PHOENIXTASK_WS_DB_HOST:=localhost}"
: "${PHOENIXTASK_WS_DB_PORT:=${PHOENIXTASK_PG_PORT}}"
: "${PHOENIXTASK_WS_DB_NAME:=phoenixtask_demo}"
: "${PHOENIXTASK_WS_DB_SCHEMA:=public}"
: "${PHOENIXTASK_WS_DB_USER:=${POSTGRES_USER}}"
: "${PHOENIXTASK_WS_DB_PASSWORD:=${POSTGRES_PASSWORD}}"

: "${PHOENIXTASK_BACKEND_PORT:=8080}"
: "${PHOENIXTASK_FRONTEND_PORT:=3000}"

: "${PHOENIXTASK_DEMO_EMAIL:=sofia.ramos@phoenixtask.demo}"
: "${PHOENIXTASK_DEMO_PASSWORD:=PhoenixTask2026!}"
: "${PHOENIXTASK_DEMO_TENANT:=demo}"

: "${PHOENIXTASK_POSTGRES_CONTAINER:=phoenixtask-postgres}"

PID_DIR="${ROOT_DIR}/.pids"
LOG_DIR="${ROOT_DIR}/logs"

export ROOT_DIR PID_DIR LOG_DIR
export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB PHOENIXTASK_PG_PORT
export PHOENIXTASK_DB_HOST PHOENIXTASK_DB_PORT PHOENIXTASK_CONTROL_DB
export PHOENIXTASK_DB_USER PHOENIXTASK_DB_PASSWORD
export PHOENIXTASK_WS_DB_HOST PHOENIXTASK_WS_DB_PORT PHOENIXTASK_WS_DB_NAME
export PHOENIXTASK_WS_DB_SCHEMA PHOENIXTASK_WS_DB_USER PHOENIXTASK_WS_DB_PASSWORD
export PHOENIXTASK_BACKEND_PORT PHOENIXTASK_FRONTEND_PORT
export PHOENIXTASK_DEMO_EMAIL PHOENIXTASK_DEMO_PASSWORD PHOENIXTASK_DEMO_TENANT
export PHOENIXTASK_POSTGRES_CONTAINER
